/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as InquireRouteImport } from './routes/inquire'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUploadProjectRouteImport } from './routes/admin/upload-project'
import { Route as AdminUploadInsightsArticleLinkRouteImport } from './routes/admin/upload-insights.article-link'
import { Route as AdminUploadInsightsBlogRouteImport } from './routes/admin/upload-insights.blog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const InquireRoute = InquireRouteImport.update({
  id: '/inquire',
  path: '/inquire',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadProjectRoute = AdminUploadProjectRouteImport.update({
  id: '/admin/upload-project',
  path: '/admin/upload-project',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadInsightsArticleLinkRoute =
  AdminUploadInsightsArticleLinkRouteImport.update({
    id: '/admin/upload-insights/article-link',
    path: '/admin/upload-insights/article-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUploadInsightsBlogRoute = AdminUploadInsightsBlogRouteImport.update({
  id: '/admin/upload-insights/blog',
  path: '/admin/upload-insights/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquire': typeof InquireRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload-project': typeof AdminUploadProjectRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/upload-insights/article-link': typeof AdminUploadInsightsArticleLinkRoute
  '/admin/upload-insights/blog': typeof AdminUploadInsightsBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquire': typeof InquireRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload-project': typeof AdminUploadProjectRoute
  '/admin': typeof AdminIndexRoute
  '/admin/upload-insights/article-link': typeof AdminUploadInsightsArticleLinkRoute
  '/admin/upload-insights/blog': typeof AdminUploadInsightsBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/inquire': typeof InquireRoute
  '/insights': typeof InsightsRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/upload-project': typeof AdminUploadProjectRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/upload-insights/article-link': typeof AdminUploadInsightsArticleLinkRoute
  '/admin/upload-insights/blog': typeof AdminUploadInsightsBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/inquire'
    | '/insights'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/upload-project'
    | '/admin/'
    | '/admin/upload-insights/article-link'
    | '/admin/upload-insights/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/inquire'
    | '/insights'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/upload-project'
    | '/admin'
    | '/admin/upload-insights/article-link'
    | '/admin/upload-insights/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/inquire'
    | '/insights'
    | '/portfolio'
    | '/sitemap.xml'
    | '/admin/settings'
    | '/admin/upload-project'
    | '/admin/'
    | '/admin/upload-insights/article-link'
    | '/admin/upload-insights/blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InquireRoute: typeof InquireRoute
  InsightsRoute: typeof InsightsRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUploadProjectRoute: typeof AdminUploadProjectRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUploadInsightsArticleLinkRoute: typeof AdminUploadInsightsArticleLinkRoute
  AdminUploadInsightsBlogRoute: typeof AdminUploadInsightsBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquire': {
      id: '/inquire'
      path: '/inquire'
      fullPath: '/inquire'
      preLoaderRoute: typeof InquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-project': {
      id: '/admin/upload-project'
      path: '/admin/upload-project'
      fullPath: '/admin/upload-project'
      preLoaderRoute: typeof AdminUploadProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-insights/article-link': {
      id: '/admin/upload-insights/article-link'
      path: '/admin/upload-insights/article-link'
      fullPath: '/admin/upload-insights/article-link'
      preLoaderRoute: typeof AdminUploadInsightsArticleLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload-insights/blog': {
      id: '/admin/upload-insights/blog'
      path: '/admin/upload-insights/blog'
      fullPath: '/admin/upload-insights/blog'
      preLoaderRoute: typeof AdminUploadInsightsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InquireRoute: InquireRoute,
  InsightsRoute: InsightsRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUploadProjectRoute: AdminUploadProjectRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUploadInsightsArticleLinkRoute: AdminUploadInsightsArticleLinkRoute,
  AdminUploadInsightsBlogRoute: AdminUploadInsightsBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
